language: haskell

before_install:
  - cabal install --only-dependencies --enable-tests
  - cabal install hpc-coveralls --avoid-reinstalls

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls --exclude-dir=tests kdb-haskell-hpc